FROM debian:bookworm AS base

WORKDIR /app

RUN dpkg --add-architecture arm64
RUN apt update
RUN apt upgrade -y
RUN apt install -y build-essential curl libssl-dev pkg-config sqlite3 python3 libpython3-dev crossbuild-essential-arm64 libssl-dev:arm64 libpython3-dev:arm64

ENV PKG_CONFIG_PATH /usr/lib/aarch64-linux-gnu/pkgconfig/
ENV PKG_CONFIG_ALLOW_CROSS 1

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target add aarch64-unknown-linux-gnu
RUN mkdir /.cargo && \
    echo '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"' >> /.cargo/config.toml

RUN cargo install cargo-chef

FROM base AS planner

COPY ./ ./

RUN cargo chef prepare --recipe-path recipe.json

FROM base as builder

COPY --from=planner /app/recipe.json recipe.json

RUN cargo chef cook --release --target aarch64-unknown-linux-gnu --recipe-path recipe.json

COPY ./ ./

ENV DATABASE_URL=sqlite:bot.db
RUN sqlite3 bot.db < migrations/20220301134633_bot.sql 

ENV PYO3_CROSS_PYTHON_VERSION 3.11
ENV PYO3_CROSS_LIB_DIR /usr/lib/python3.11

RUN mkdir -p /app/bin
RUN cargo build --release --target aarch64-unknown-linux-gnu
RUN mv ./target/aarch64-unknown-linux-gnu/release /app/bin/tgtg-discord-bot

FROM debian:bookworm as runner

COPY requirements.txt /
COPY --from=builder /app/bin/tgtg-discord-bot /usr/bin/

RUN dpkg --add-architecture arm64
RUN apt update
RUN apt upgrade -y
RUN apt install -y python3 python3-pip libpython3-dev libpython3-dev:arm64

RUN pip install -r requirements.txt --break-system-packages

ENTRYPOINT [ "tgtg-discord-bot" ]