name: Audit
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Check | Audit
        run: cargo audit