name: Audit
on:
  pull_request:
    paths:
      - Cargo.toml
  schedule:
    - cron: '0 0 1 * *'

jobs:
  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Check | Audit
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
