name: Create Release Builds

on:
  push:
    tags:
      - "v*" # matches v1.0.1, v1.2, v2, etc

env:
  CARGO_TERM_COLOR: always
  
jobs:
  once:
    name: Create GitHub release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
  build_x86_64:
    name: Create a release build, tag and upload binary for x64
    needs: once
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:bot.db
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Python dependencies
      run: |
        pip install --user -r requirements.txt
    - name: DB Migrations
      run: |
        sqlite3 bot.db < migrations/20220301134633_bot.sql
    - name: Build release version
      run: cargo build --release
    - name: Make Zip
      run: 
        7z a -tzip ${{ github.workspace }}/target/release/tgtg-discord-bot-linux-x64.zip ${{ github.workspace }}/target/release/tgtg-discord-bot* "-x!*.d" "-x!*.pdb"
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.once.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/target/release/tgtg-discord-bot-linux-x64.zip
        asset_name: tgtg-discord-bot-linux-x64.zip
        asset_content_type: application/octet-stream
  build_arm64:
    name: Create a release build, tag and upload binary for arm64
    needs: once
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image for one stage
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.arm64
        context: .
        target: builder
        tags:
          tgtg-arm64:latest
    - name: Extract binaries from the docker
      run: |
        mkdir -p ${{ github.workspace }}/bin
        docker cp $(docker create tgtg-arm64:latest):/app/bin/. ${{ github.workspace }}/bin
    - name: Make Zip(s)
      run: |
        7z a -tzip ${{ github.workspace }}/bin/app/tgtg-discord-bot-arm64.zip ${{ github.workspace }}/bin/tgtg-discord-bot
    - name: Upload Release Asset Client
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.once.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/bin/tgtg-discord-bot-arm64.zip 
        asset_name: tgtg-discord-bot-linux-arm64.zip 
        asset_content_type: application/octet-stream
  build_armhf:
    name: Create a release build, tag and upload binary for armhf
    needs: once
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image for one stage
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.armhf
        context: .
        target: builder
        tags:
          tgtg-armhf:latest
    - name: Extract binaries from the docker
      run: |
        mkdir -p ${{ github.workspace }}/bin
        docker cp $(docker create tgtg-armhf:latest):/app/bin/. ${{ github.workspace }}/bin
    - name: Make Zip(s)
      run: |
        7z a -tzip ${{ github.workspace }}/bin/app/tgtg-discord-bot-armhf.zip ${{ github.workspace }}/bin/tgtg-discord-bot
    - name: Upload Release Asset Client
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.once.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/bin/tgtg-discord-bot-armhf.zip 
        asset_name: tgtg-discord-bot-linux-armhf.zip 
        asset_content_type: application/octet-stream